# Generated by Django 5.0.1 on 2024-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='car_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
