# Generated by Django 5.0.1 on 2024-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='google',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(max_length=100),
        ),
    ]
