# Generated by Django 5.0.1 on 2024-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_car_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='cars.feature'),
        ),
    ]
