# Generated by Django 5.0.1 on 2024-01-19 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.image'),
        ),
    ]
