# Generated by Django 5.0.1 on 2024-01-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_description_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sale',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Sale', max_length=100),
        ),
    ]
