# Generated by Django 5.0.1 on 2024-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('MUV/SUV', 'MUV/SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Jeep', 'Jeep')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('Bad', 'Bad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic')], max_length=100),
        ),
    ]
