# Generated by Django 5.0.1 on 2024-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_vin_no_alter_car_body_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
